"""add external_id to jobs, drop unique on url

Revision ID: 644d9c0cf2bb
Revises: 0ed0a34b8433
Create Date: 2026-09-09 23:03:47.921887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644d9c0cf2bb'
down_revision: Union[str, Sequence[str], None] = '0ed0a34b8433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_jobs_url'), table_name='jobs')
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_url'), 'jobs', ['url'], unique=True)
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
